import type { SourceEntry } from "@/lib/types";

export const sources: SourceEntry[] = [
  { id: 2, label: "Adolescent search patterns: pads, pods, cups, and discs" },
  { id: 3, label: "Vulvovaginal epithelium and systemic absorption pathways" },
  { id: 5, label: "Lifetime menstrual product utilization estimates" },
  { id: 6, label: "Single-use product exposure modeling" },
  { id: 7, label: "Cumulative tissue contact duration" },
  { id: 8, label: "Adolescent development and reproductive health sensitivity" },
  { id: 11, label: "PFAS prevalence in period underwear testing" },
  { id: 12, label: "PFAS prevalence in reusable pad testing" },
  { id: 14, label: "Total fluorine concentrations in reusable textiles" },
  { id: 15, label: "High-concentration PFAS textile findings" },
  { id: 16, label: "Spencer, et al. v. Knix Wear Inc. class-action filing" },
  { id: 17, label: "False PFAS-free advertising penalties" },
  { id: 20, label: "Global VOC testing in disposable pads" },
  { id: 21, label: "Xylene detection rates" },
  { id: 22, label: "Toluene detection rates" },
  { id: 23, label: "Methylene chloride detection rates" },
  { id: 24, label: "Inter-brand VOC concentration variance" },
  { id: 27, label: "Phthalate plasticizer leaching under physiological conditions" },
  { id: 28, label: "Dibutyl phthalate (DBP) migration studies" },
  { id: 39, label: "Low-dose environmental phthalate exposure ranges" },
  { id: 40, label: "Non-linear reproductive toxicity thresholds" },
  { id: 41, label: "Endocrine receptor range matching" },
  { id: 44, label: "UC Berkeley 2024 tampon heavy metals study" },
  { id: 45, label: "Lead detection in tampon samples" },
  { id: 46, label: "Cadmium concentrations in tampons" },
  { id: 47, label: "Arsenic concentrations in tampons" },
  { id: 48, label: "Mean lead concentration (120 ppb)" },
  { id: 52, label: "Organic vs. non-organic tampon metal profiles" },
  { id: 55, label: "Health Canada medical device classification" },
  { id: 56, label: "Internal product change intervals and TSS guidance" },
  { id: 57, label: "Canadian ingredient disclosure requirements" },
  { id: 58, label: "New York mandatory disclosure law" },
  { id: 59, label: "California mandatory disclosure law" },
  { id: 62, label: "Federal workplace menstrual product mandate (Dec 15, 2023)" },
  { id: 64, label: "Organic topsheet vs. synthetic core marketing" },
  { id: 65, label: "Chlorine-bleached pulp core concerns" },
  { id: 69, label: "Global Organic Textile Standard (GOTS) Organic grade" },
  { id: 70, label: "GOTS Made with Organic grade (70% threshold)" },
  { id: 71, label: "GOTS certification fiber requirements" },
  { id: 75, label: "OEKO-TEX Standard 100 substance screening" },
  { id: 76, label: "OEKO-TEX Total Fluorine limits" },
  { id: 77, label: "Hidden PFAS detection via OEKO-TEX" },
  { id: 78, label: "OEKO-TEX 100+ substance panel" },
  { id: 81, label: "Health Canada menstrual cup approvals" },
  { id: 82, label: "US menstrual cup brand registrations" },
  { id: 85, label: "Canadian market verified brand screening" },
  { id: 86, label: "Verified Canadian brand product profiles" },
  { id: 90, label: "Fragrance mixtures and hidden VOC/phthalate fixatives" },
  { id: 92, label: "Organic topsheet verification guidance" },
  { id: 96, label: "Web Share API and mobile native sharing" },
  { id: 98, label: "Hygiene practices and TSS risk reduction" },
];

export const sourceMap = new Map(sources.map((source) => [source.id, source]));

export function getSourceLabel(id: number): string {
  return sourceMap.get(id)?.label ?? `Source ${id}`;
}
